Name = "Arcrylic"
Version = "1.0.0"
Description = "A module to apply acrylic blur effect to Windows application windows"
Author = "Wnclient Dev Team"
Dependence = ["ctypes"]
platforms = ["Windows"]
UseThreads = false